development:
  client_id: 269717343442-b3ol9p9jvmed4iq1qf2qejnnocp9f3tr.apps.googleusercontent.com
  client_secret: dVuMD13MwHQJA9D0x-J2vYDh
production:
  client_id: 269717343442-b3ol9p9jvmed4iq1qf2qejnnocp9f3tr.apps.googleusercontent.com
  client_secret: dVuMD13MwHQJA9D0x-J2vYDh
