development:
  GOOGLE_CLIENT_ID: 269717343442-b3ol9p9jvmed4iq1qf2qejnnocp9f3tr.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: dVuMD13MwHQJA9D0x-J2vYDh
production:
  GOOGLE_CLIENT_ID: 269717343442-b3ol9p9jvmed4iq1qf2qejnnocp9f3tr.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: dVuMD13MwHQJA9D0x-J2vYDh
