# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9afe34d1dd17fc81ceda4a7e1de37b1dfedd6abfca6a12afbb3b0d17da9a77858d971c662015449b72fefafb41cc06da7ceda417dd839cfe921cbb3537449bc
  
test:
  secret_key_base: ceeca3f8f0b489a387482db953d1b2cbd35f1fc0ff33bbbe4355ae60f05cc3c18e14cc99de1071631fbb45440e3b372d91be48d3168e9fdd20ba9a3f8f2065ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>




development:
  client_id: 269717343442-b3ol9p9jvmed4iq1qf2qejnnocp9f3tr.apps.googleusercontent.com
  client_secret: dVuMD13MwHQJA9D0x-J2vYDh
production:
  client_id: 269717343442-b3ol9p9jvmed4iq1qf2qejnnocp9f3tr.apps.googleusercontent.com
  client_secret: dVuMD13MwHQJA9D0x-J2vYDh  
